# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 27bd9c2f6d4ea89fd42387e88e58cf8ddba1df6f522563491fd5dfdb6639850e3295dd33dfb658483346162eae319344959edf24caacf8c64c9f6f5cdd48fc3a

test:
  secret_key_base: a1604fda0dc2f87e5288445da9d0e0828ccf30e3b80984825a66e3c007be105a62205da051ba2540be84c9e3ca381dd26f4422780e6bfd6c4b6c790e612868cd

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
